### ISSUE TITLE
❌  fork/exec /root/.dapr/bin/daprd: no such file or directory

### ISSUE THREAD

**Issue by sharadregoti** [dapr/cli#974] opened 2022-05-05 15:51 UTC
## Expected Behavior
Launch a Dapr sidecar that will listen on port 3500 for a blank application named myapp:

## Actual Behavior
As per the getting started docs, After running `dapr init`. I had to run this command `dapr run --app-id myapp --dapr-http-port 3500`

But the above step failed.
There are multiple behaviours that i want to highlight
1) After running dapr init command, I am not able to run `dapr` commands directly
`dapr` command just gets stuck on the terminal. I have to press ctrl + c to exit
2) dapr commands started working if use `sudo`
After running this command `sudo dapr run --app-id myapp --dapr-http-port 3500`
I got this output
```
WARNING: no application command found.
❌  stat /root/.dapr/components: no such file or directory
```
3) I tried to fix the above error by using this command 
` sudo dapr run --app-id myapp --dapr-http-port 3500 --components-path /home/sharad/.dapr/components/`
But then i got this error
```
ℹ️  Starting Dapr with id myapp. HTTP Port: 3500. gRPC Port: 37037
❌  fork/exec /root/.dapr/bin/daprd: no such file or directory
```

## Steps to Reproduce the Problem
1) Download the latest dapr cli
2) Run `dapr init`
The above command result with the following output
```
⌛  Making the jump to hyperspace...
ℹ️  Container images will be pulled from Docker Hub
ℹ️  Installing runtime version 1.7.2
↘  Downloading binaries and setting up components...
Dapr runtime installed to /home/sharad/.dapr/bin, you may run the following to add it to your path if you want to run daprd directly:
    export PATH=$PATH:/home/sharad/.dapr/bin
✅  Downloading binaries and setting up components...
✅  Downloaded binaries and completed components set up.
ℹ️  daprd binary has been installed to /home/sharad/.dapr/bin.
ℹ️  dapr_placement container is running.
ℹ️  dapr_redis container is running.
ℹ️  dapr_zipkin container is running.
ℹ️  Use `docker ps` to check running containers.
✅  Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started
```
3) Export the path as specified in the logs
`export PATH=$PATH:/home/sharad/.dapr/bin`

4) Run the dapr run command
`dapr run --app-id myapp --dapr-http-port 3500`

## Dapr Version
```
❯ sudo dapr --version
CLI version: 1.7.0
Runtime version: n/a
```

OS: Windows 10, wsl2

**Comment by pravinpushkar** [comment] 2022-05-12 12:12
@sharadregoti 
I followed the exact same steps as you mentioned in the steps to reproduce, I could not reproduce this.
Can you please try to execute the steps without sudo. Ideally after doing `dapr init` running this command  `dapr --version` should produce correct cli and runtime versions.

**Comment by shubham1172** [comment] 2022-08-01 01:58
Shall we close this due to inactivity? /cc @mukundansundar

**Comment by mukundansundar** [comment] 2022-08-25 10:51
closing due to this issue not being reproducible. Please open a new issue if this issue persists. @sharadregoti

**Closed by mukundansundar** 2022-08-25 10:51 UTC
Labels: kind/bug, not-reproducible

**Comment by guybartal** [comment] 2024-09-13 15:18
happened to me now
