### ISSUE TITLE
DAPR CLI - Windows Installer with Winget tool

### ISSUE THREAD

**Issue by rabollin** [dapr/cli#1030] opened 2022-07-20 12:38 UTC
## Create a proper installer package for Windows CLI using Winget tool. 

The winget command line tool enables users to discover, install, upgrade, remove and configure applications on Windows 10 and Windows 11 computers. This tool is the client interface to the Windows Package Manager service.

windows Dapr CLI is given as powershell script that requires multiple steps to be followed by user. One has to set the path variable and run the script. Using Winget package the multiple steps to a single executable will simplify the end user deployment steps.

**Comment by mukundansundar** [comment] 2022-07-20 12:54
duplicate of #424 . @rabollin Please assign that to yourself.

**Closed by mukundansundar** 2022-07-20 12:54 UTC
