### ISSUE TITLE
--dapr-http-max-request-size flag is missing for Dapr run

### ISSUE THREAD

**Issue by mtaghavi2005** [dapr/cli#651] opened 2021-03-31 06:00 UTC
## Expected Behavior

Since Dapr 1.0.0 there is a flag/configuration to set Max Http Request Size for dapr runtime. Although Documentation says new flag should be working with Dapr CLI, but it doesn't work.

https://docs.dapr.io/operations/configuration/increase-request-size/
`dapr run --dapr-http-max-request-size 16 node app.js`

## Actual Behavior

![image](https://user-images.githubusercontent.com/1976118/113097107-ad469b00-91f6-11eb-9cc1-6882a0be3c76.png)

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment] 2021-05-13 17:43
duplicate of #699

**Closed by mukundansundar** 2021-05-13 17:43 UTC
Labels: kind/bug
