### ISSUE TITLE
Set up State Stores and Pub Sub on k8s

### ISSUE THREAD

**Issue by yaron2** [dapr/cli#51] opened 2019-09-03 19:49 UTC
Allow users a more streamlined getting started experience using the cli, by having a `setup` command install Redis on a k8s cluster and set up the component yaml automatically on behalf of the user.

**Comment by abhirockzz** [comment] 2020-01-08 14:28
This is similar to #90? Additional details would help

**Comment by amanbha** [comment] 2020-03-25 17:19
closing as dupe of https://github.com/dapr/cli/issues/90

**Closed by amanbha** 2020-03-25 17:19 UTC
