### ISSUE TITLE
Avoid Github API rate limit

### ISSUE THREAD

**Issue by daixiang0** [dapr/cli#735] opened 2021-06-08 07:16 UTC
## Describe the proposal

Now we use https://api.github.com/repos/dapr/dapr/releases to get latest version, which would get api rate limit, details see [doc](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting).

To avoid this limit, we can add a endpoint like `/latestversion` in `dapr.io`.

It would be updated when release.

I am not sure where the website host, but it is easy to do I think.

## Release Note

RELEASE NOTE: **FIX** avoid Github API rate limit

**Comment by wcs1only** [comment] 2021-07-13 23:28
Dupe of #677. Should be fixed already via: #758

**Closed by wcs1only** 2021-07-13 23:28 UTC
