### ISSUE TITLE
`dapr status -k` does not work on Windows with KUBECONFIG set

### ISSUE THREAD

**Issue by robvet** [dapr/cli#779] opened 2021-08-09 01:18 UTC
Hello Dapr Community...

Trying to initialize a Kubernetes cluster for Dapr on Windows 10:

     dapr init -k

I get the follow error message:

   Deploying the Dapr control plane to your cluster...
   can't connect to a Kubernetes cluster: multiple 
   kubeconfigs in KUBECONFIG environment v 
   ariable -
C:\Users<me>.kube\config

Behavior is consistent across Git Bash, Ubuntu with WSL2, and PowerShell

Any suggestions for troubleshooting/resolution would be appreciated.

Thanks

**Comment by yaron2** [comment] 2021-08-11 16:03
@mukundansundar can you please look at this?

**Comment by mukundansundar** [comment] 2021-08-17 10:11
@yaron2 I will take a look at it today ...

**Comment by robvet** [comment] 2021-09-03 22:54
Can we possibly get some tracition on this issue? It's beeen a month.

**Comment by LKI** [comment] 2021-09-10 03:24
> Unfortunately, that's not helping. Through hacking at it, discovered that if I open a command shell in admin mode (either PowerShell or GitBash), the ‘dapr status -k’ command works correctly. But, if open the same command shell without admin mode (either PowerShell or GitBash), the ‘dapr status -k’ command errors with the ‘multiple contexts’ error.
> 
> Have not seen the 'Multiple Contexts' error on any direct kubectl command, only on Dapr commands for Kubernetes: Dapr init -k, Dapr status -k

Confirmed.

Same error here, and hacked by using [sudo](http://blog.lukesampson.com/sudo-for-windows) (Admin permission).

```
❯ dapr status -k
multiple kubeconfigs in KUBECONFIG environment variable - C:/Users/LKI/.kube/config

❯ sudo dapr status -k
  NAME                   NAMESPACE  HEALTHY  STATUS   REPLICAS  VERSION  AGE  CREATED
  dapr-operator          dapr       True     Running  1         1.3.0    8m   2021-09-10 11:14.41
  dapr-sidecar-injector  dapr       True     Running  1         1.3.0    8m   2021-09-10 11:14.41
  dapr-sentry            dapr       True     Running  1         1.3.0    8m   2021-09-10 11:14.41
  dapr-dashboard         dapr       True     Running  1         0.7.0    8m   2021-09-10 11:14.41
  dapr-placement-server  dapr       True     Running  1         1.3.0    8m   2021-09-10 11:14.41
```

**Comment by LKI** [comment] 2021-09-14 09:17
Looks like root cause is following code:

https://github.com/dapr/cli/blob/909b989128499274720ff0cc46b93dcbfc77a394/pkg/kubernetes/client.go#L53-L62

`KUBECONFIG` environment variable under Windows is something like `C:\Users\LKI\.kube\config`.
But the delimiter is `:`, so the check will return an error.

**Comment by sandeshkg** [comment] 2021-11-10 05:22
Can i work on this one? I have looked at the kubernetes docs here - https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/ and it says - 
"The KUBECONFIG environment variable is a list of paths to configuration files. The list is colon-delimited for Linux and Mac, and semicolon-delimited for Windows"
Currently the kubeConfigDelimiter is set to ":" always. We would need to set the kubeConfigDelimiter based on os. 
Please do let me know if my understanding is correct and if i can proceed on same lines.

**Comment by yaron2** [comment] 2021-12-22 23:09
> Can i work on this one? I have looked at the kubernetes docs here - https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/ and it says - "The KUBECONFIG environment variable is a list of paths to configuration files. The list is colon-delimited for Linux and Mac, and semicolon-delimited for Windows" Currently the kubeConfigDelimiter is set to ":" always. We would need to set the kubeConfigDelimiter based on os. Please do let me know if my understanding is correct and if i can proceed on same lines.

This is now closed via https://github.com/dapr/cli/pull/834, but we'd be very happy to have you work on other things! :)

**Closed** 2021-12-22 23:08 UTC
Labels: good first issue
